#ENC[AES256_GCM,data:Sz1YNw3uOdhtQvTkpJb3IGwYoin45oHXtrSsPTWL9iDMq8v+YFDgLxLV0pUAOK5015xGCv12YqvKfxFN9NdwOXMyrtu8+L4SPZSjkxaWv0/jJFe4LYCRW6AIB+xqvii2vTOqNFnc0o0FelWfQfMBwxW/A9h6CeiM/EkxlMglkNdH,iv:aBBbPvHpucjMbkWVvFKojO7NeurCeU6JiiQQgW8TxOw=,tag:b0n4KYXlceXWfdnRpg+IBQ==,type:comment]
#ENC[AES256_GCM,data:TdzLocEmNszAQgLDDBP25os5I57Rb0usLrLEcnpc/nqHRGN9sNJOvr8LbcxCpdgU47CVfy/raYD0zz0Fhw==,iv:plqZH1j3gSuL5bY7NRlv3KgXTK2laUigYlJBTMIaQV0=,tag:/cZrvJa5PVnDrBKnQac/fA==,type:comment]
#ENC[AES256_GCM,data:ZA6j6wE4pWLQFGe6wEE+l957AnUArZChhLvUvsONao+1hZVwHQ==,iv:eLMfQ2lAYiAiEjkhKqliMXhYx/JiuvK6QEUnlHxj5Hc=,tag:OPOdIBPMfe9oj6fbVVuVgQ==,type:comment]
#
#ENC[AES256_GCM,data:MGfYD8JgVdW4OxixSGYBHbQ2Ow4OucAZqVnJMOkESx4e8rXD8WGMdz1IL2XXklu1SliZdOO2r+eTH930n8LcIvJ6BzcvKHYd/XjY3CKgVIEURvex/23ncy6RMjauMWAf4Q==,iv:r5ooSnwQKDd13YbLhvxI/erROa1SLb+6c48afKZI0ME=,tag:PdR9v6duSQUA5/YTWQA9wg==,type:comment]
#ENC[AES256_GCM,data:ANjv441SgqMR5a/GfxvPYPNiS4CKa5Z7mYTEyeDGojCcdOqXtKRndRL/T/iIMzJeUu9Ha+U8UTx5mmknx5aZj9ksAgY6BngjQhWZBJHkbbnijeS+fQDJc036y26eX4ijiy/RfOjdZBf0rDm1F/phI2ls8YoIrgMUfikZFlPtW5gwUw==,iv:/Ai8OU4YHXDBnRHJsV+H36YqseAewRXCeIdJ6Vrja88=,tag:pjrHJ1S4xnUzMuovINNSDA==,type:comment]
#ENC[AES256_GCM,data:gJOZbCAdeizzwjXGccL1DMsKMjdahIt0e3f6j1lJEw==,iv:UJDmi2GQ0gQZGQ8kAUgt1yu1Qbit3/nNDcqVVPosMhM=,tag:PS4OZzMaBSdDpa/IC9zHvw==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:6fUDkg==,iv:CqR6VpjRjsNF6HOuvxxFIOg5RZ1fAm+RJIyde+bQ8YA=,tag:6dUj0u3rwCKA8uLVSE+bdw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:2QcGZqKiCI8HUde5tw==,iv:M9B6BLUMVs5nZ6H65z2vMirtRMmiOCWciM1md2YrFG0=,tag:GRQ/hN87WwEK6Fiv5TAduQ==,type:str]
sops:
    age:
        - recipient: age1su8ukc9xm5ffg4trtcsmtw08spr2dxwafkf6zn3znpjwnejkn5tq0a93ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0xYQXhKVkUrcWRVOU82
            STFqdzJrdUN4cVpVUUorejdabnFTRWtqZm1rCnR1VE1ZMm1ENDdiaDJFVWp6SVJ6
            SDhJdDRRUjc5MEg0YXZNdDNLVXJQQUkKLS0tICtUWjdwb1Z1OG10UzNMSnR1MUZI
            V1pmYlcyZm9ZcDFQVm9jbHZCOStEYlEK9Hss8V+p2+W74b0Gc+YWqPzq7HI98lyU
            aKT2/yvvvNxBsHGkaLC11kk3WqgUkXGC4wOlwHNCNHd6+C45l4w9fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T06:32:55Z"
    mac: ENC[AES256_GCM,data:VFvHFcZwiLhCTk4YWPF4+zeADazFYChYEgoIIR0MwU7fVJbryZ593X2a+K3q30TOBblkbaniucqy5inYl5a6J8xVp1+Bthca0yQAhrOzB28n7Zoij1gmJz4FyB3VmkFxlYWb9X5KoYGYvAff/cdx1/gZMDlX9Sm8MbLX0BSYFdw=,iv:bWVJ+LUsU4dn3cNrmnahi/rO5n+Z85N1DvcKLJju8LE=,tag:9yRL2oOxCDvwccZU1HpxVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
