#ENC[AES256_GCM,data:3cdgOToQI+1J58yiGpX6pK4nFHSlxUad7ji+OmKfrEIcCkCtlbYIZpfL9rZxsMrVD2tHFEMjp1JU2JTTApPBcc+zmUvOWnSRLux874kA8DYe8hUg0yc/xn6bjT5CmHThchbQoEsX+4bdrV923HfqUBYSF0iroh2UADaJV3iOU+pq,iv:bPLR2ctumKHHQcO8Kc7ivqOI3y0LW4yHHzgJtdT/Dk0=,tag:VwJ7HzGq/mVGX5xyOrpyWQ==,type:comment]
#ENC[AES256_GCM,data:nTXXGtEZShjun4tfoXywPSHCRgK6eJhMRI0Smskts5lusDsxL/UxYoL/7Jc1ulMbsmbB/scSNYuGcTuRrQ==,iv:ZFPFvbnI5j0zWB4C9tE77vREe/TuXgC3kEpAZ2GkicA=,tag:6eq3kzKe4BrsJwf34oyOIA==,type:comment]
#ENC[AES256_GCM,data:1p8Qv7JLnI5JRW19UuikE0+yv05VQMQY3RB35dcIPiVZJpahHg==,iv:UrmmwybI+HYWHkgOjlEyjdUI+iA4I0CZg8h7h3cFeKc=,tag:Kf5ixr7xpTOSj40/EqEcRg==,type:comment]
#
#ENC[AES256_GCM,data:SxnWJKSnsKwBxOhEdtT8x1qRg11JBbHzY2+p7tqJTlXYLIDKEEVYa5M4sQMEr8BuUxLs4XPMxgmo7Gdsyd2jVw9zFl8SPrnlqXuXUOESUAUkQk8CFi0EnsA50fMMDSqLuw==,iv:QDe9RhOOghYP/+DWuWsXsERklO+OxDir67uXtMuK2ww=,tag:9PG/UDZTkD7HCMfCtqPx9g==,type:comment]
#ENC[AES256_GCM,data:M3CFtXhzWS5fTTdfhNYfqbM7DjW4APk/h9u43VI3AJ+Vn+ax3r5BS3RhpzR/oL03KA+r0cuCrFUf+AXqfnayFC5jDUCy9PF4TUlBaf4AWvXiFjoI+cjv3nOmobQqfMxP1qitesoC/TNLfraDAlzv1gtA4y5rEMwAucEgkA1nA+ap+w==,iv:OZRjsk5egXWs87rdCVhrQ+/jAqk2XU50qZXAbeJkZ1E=,tag:8bcT037rj66Inwb3PiZ1nw==,type:comment]
#ENC[AES256_GCM,data:QzeSkxKxGBnDd4an/eEfIA/SyncoxHs6csqD7iE0ZQ==,iv:w89PxP33unsG6/9n00uRsCQUW7qCCAStpPXph/P9cJI=,tag:BAs4JYJo2ynUhfd47fE9TQ==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:hv7bf/0=,iv:guP3bVQWEB3QBGVNyda2KFuyHDjKgfvR0C9tVabeeZw=,tag:vx2L3pbW4z3ODllxGcLQYw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:dVT2OQ==,iv:GySqGYt2R4LG6w4tV3Iowo/DCyqYH6DI6Bxd2fkx0DA=,tag:NtbqVVp3ZEgE2V8rPaUjPQ==,type:str]
sops:
    age:
        - recipient: age1su8ukc9xm5ffg4trtcsmtw08spr2dxwafkf6zn3znpjwnejkn5tq0a93ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZHpsS2RmTHFyLytSWDUx
            RDE2Q2l1UmlpRklvOGpIVXRyV1dYenh5L2xjCjhEbmRMNnZtZHYvd2QxUm9GY0w0
            dGlzNFlEcWdoZW9YVER6RGQ0b0pkd2MKLS0tIFBBeXFQMUZaY01zMEhqM29XdWFv
            UjdDZjVmaGg0ZnppY3RtaTVTUjlNQmcKa31yugqKuBBsIxzvJ3xCI3bcT1Y/ih8Z
            P0847XpcLgqjofC13785DNFDsQUfBCQByen34hb1rXd+9saMMxVhqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T20:23:12Z"
    mac: ENC[AES256_GCM,data:9NgiX975riFkR6mL3nDDwYN9U/4kvTGxmSJdgZgdmsxp5yPh4hRQVNxVJixhv8j3Xv0xE8viUURWi29WCymDNiyH3o4SzyTUcjxDgzzIatBXuphwrR9OJkhWSXAtpWLcdFjAX4SPRew8zEX8/nfZfZTwknoVxbj0vhuaI+zMhoA=,iv:E+VYatfPgkwBTZPpx/Ahn5TeUaK42NNMq4CKFCeroeU=,tag:7T5jg1K0dlThLGf3OSp+nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
