#ENC[AES256_GCM,data:EnraAVFhruHq2eYLRDmDj8mRXxBdlpS6pCovHOWgZgAE3oIbYnjNjVpscHB6jKr0KGUr2wyzbiwfABow4TZn1Ie02XJYwIm9TxkTJMxMS7O0XDvyvcbvdjQEQ0/1YiRi89/yjlM1OC9/usHWF8gj5h+/Hd+f0FsCTUMFlnfxk8+m,iv:b++9NGW8hszvDKjgZZIUqYh4YUzuxSuBNwmxgikQXzs=,tag:HGbMZCMI7hzFiR0M6DUfnQ==,type:comment]
#ENC[AES256_GCM,data:xMfdCiGnux71MynzUpJTXaRGxc106Q4aRscAe+cN2kl+rLKesn9aBWwZi043ug+4U/BOvryMpRzGnh+wyw==,iv:Q7D5bD+WqGI0xd2DPlY/MhhwOPmlVsqdkMXzpmAXt8A=,tag:ojwPHKy4gSR49Gg6miYuNQ==,type:comment]
#ENC[AES256_GCM,data:5vTbFrJGu1agDnGfr1AUt3TVKVf9oMVfcIWDgQRK8d/+bq1+5A==,iv:QitJ/Kict2pXJTpXfI2PQP6FLnsEUb3ZbJuIx1nWl6I=,tag:TX6x/UfnNpNx0dFWuvzKJQ==,type:comment]
#
#ENC[AES256_GCM,data:nQykOXZfZo6FimxaaZ7mCCJcL/m/QskjvTJfJCbiDL/tXMSAIg6XgwZZKrOccmshX+Pc3o7mlFlUoitOpBH93xB2YdF2/bcGjrsN3vsw1BDYDj2tx6jltGSuNB6q1zd8JA==,iv:QK4ZM6WA96MZX0g2xUPgip//LjDg7pO2h4jNfXzWKIo=,tag:n3kUpdpvGIP3hDxA8xcO4w==,type:comment]
#ENC[AES256_GCM,data:XwCUKa/SFbG6du8e1eW3iUzN6inwC3SK2tzflTKyRvXeLVdZLtHrskO4e+rddIf9AfX7gtWTE+qoYq0303wTGVm94aYb4FPy7A0mV7FAsv64zEA9LHjYkDUQzhm3tCJTicapLPYxXeHyTXvSvocZ+/0NHQX5n7zcy4CWML+4vo30HQ==,iv:wCuwt4lHK0h+vbr4WMZGB8WpIZlqJ8fwajFoeYhC3VU=,tag:mGx/xXA/4VvCzye3f/Vwow==,type:comment]
#ENC[AES256_GCM,data:yUnV7umVV8rRcILZnKtqyy3rifn9mXijwoBenhV3Fw==,iv:7KqpIujVOfQzPUFWCuURywoUKjS9LwRBknHE93cRRJk=,tag:y8I38GqwSu8WystJJGszQQ==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:GWj+zA==,iv:RtZBFWCsQTKErGWhNkWRX10wVrPMgmt5M1AEPEWgkDc=,tag:ahu3TcNaQ66G5Ez2H4rKtA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ViUUh+K+E6iEhwUSWw==,iv:Y7u8BrEjsYxwjMVLkd08pQKXJ25UJxSDYj4Ik+wh46s=,tag:vi2f8jZ+F1dgk1IDl4LQUQ==,type:str]
sops:
    age:
        - recipient: age12d3npz4tvr9tl8d90dqzaqudqdneegk9gyxv4e8rtleu2g74ld6q3spxdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZODgwZkRMVEhjVlptWmgr
            VVplcXVtUnF5dkVlNSt4MVhlNE9pSEpldWt3ClgzUHJVSmQySFcwYmpSZWl4ODZG
            U2RLbFUxbXRkdUdnNWZGSzlJRG5XZE0KLS0tIGVlL2RHbnd4TUI0bG9ZQUVVd3BV
            SUpWb2U0dkZOUi9mM3VDMUJZZ0VMS28KWzT64DISp32+DZhxIJfwiuSX/aGqjhQf
            vnTVR3v9zfUd3ve5IOKtXoTipNB/jnXD7SDtbwH3ENtt42IIFvaIwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T09:43:02Z"
    mac: ENC[AES256_GCM,data:y//JMmYuaL2vDv3qvmYKkgkUaKjZaBtJRu6AVFoNEwnAWeazmHnpzN7xZrMa46R8+1FYZJGPjNfncfffHO6iS8ISHdcZ+RmSNib4MIuAGs7lXfzwhfKHFnUANiLa5Hgbgks/j3j9WZOZSw5FW/eZRkfqeEp0q2GHNFCTO+Fsino=,iv:TSqypQPqDaP2s1Y569E/RevqrrXcczioM5xUSUsacr4=,tag:igyuLxe1QPI/4rR5cltmhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
