#ENC[AES256_GCM,data:IRy1XUglMe9aXWZVx/M8igYUHVxsV+S9yoHc844oissN76WwjOMI7HAexcUnd+OQgFvQv0zVlHdCne/2VpXcekrswjNpwHRl6AzBmrs4A1mfK95nH/Cg7fflx7tCTMHRpGKF73/wXmB3jovKPRSObD00swT17pU+V6umTgslQwk=,iv:J7xbRWrCxjoeK64IlwcEZXudE5JcZx00QfgosVaN3Kw=,tag:fhaSC/TFJ4wxZWKyQNhsDA==,type:comment]
#ENC[AES256_GCM,data:6yUbArzXKWnDSSyPqZgcN+JdIkG+4EfAfGHlgIdlZPwtb9cQ9BHs1fZzS7oLC5FhbTYVpVEfpJxkELPOV8Ir1ah2Gbtk1f1sttVPydrKweGUjPiyneBJX8jftD4b4fuFJJfmJ51KDd5Svh+ze+kZ3mZmjKBv7zEG,iv:2V+f8zZ+AA8lfYTonai75VeZw3A4V2udOStmqi5aT7w=,tag:CFEEhSJzNRjGbMSHu0y5eQ==,type:comment]
#
#ENC[AES256_GCM,data:/LXnsHFABZhbIacHFeB1A77HWfWWpYVJHbS5dFXSl7+4yS+QUvFcr7l4oZvfFxuwFHqZdvnzBvaLzXlq62QtzzlgDQ==,iv:HNTW+ZQ8KN8Pd4lgAjYUINfgOU9AU6Oy4bSJRiFXs2w=,tag:tcvat2KzGELVaSa56Kcsgg==,type:comment]
#ENC[AES256_GCM,data:Bm4k3uI8JEydGOfz6Ag8Xn4hibCJXluIvnSliCpqsvp6xK32rBybDw==,iv:Gld8vAIWS8VdXEEW/vslp4dQ226RX3/iqBZNHDBwpYk=,tag:zwpMZBWBWdiI5YWxouJA9g==,type:comment]
#
#ENC[AES256_GCM,data:Dj52RPNSsyCZ9E6SymM9+SDz2yDJ4q+FYWA4CBhHJJbiZ4WG/1Pj5nFBfpOoGXfcfOXvUcSUMsU0kZQEIBOhoK9h0YtWpcI7+FEAgWEPxn6MiVV7QoXrkaA+obDhdbWKUeLgMu3KbM92ZJ2pIw8d7axArvfd,iv:9Y+Tbg3evduHyTsxE1UUdYD98YCelDmp6Fpb32dZdws=,tag:9dO87QjIdMwCWhWJ+3QEWA==,type:comment]
#ENC[AES256_GCM,data:vGxBWP06fOSeZYfwXv6pXQ5UB76pHSijLcEtYP2FSFPtRcJHLkcEaxSwk/NzqhUCjmdjyG79xoAB7Ct2bjGpvF9v/YSX26xR6Nw6d41d33ZWE2v/CSsK0CFVdw564Xb6BOlgMi4eqYOi2PbzMpU0jD2pEcmAn8/AaNrjQy/L17RLThRB4QzoKC/GYLR8sla+kuDNmT4=,iv:GpOUI/aQCZiiJMWE7LKRXCzL0jBToJtQCO8f1GeuRtg=,tag:kgZBXzHv71SagfizI/z8VA==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:dq2NYwU=,iv:oLBUPIPc4UWb9LY2NidlkctI4Eng/mjxnbNbI+QiIlM=,tag:FWu2g5y8CLQiiWsOXgag8w==,type:str]
    dbPassword: ENC[AES256_GCM,data:v+7zfg==,iv:f82/ptKb9WRbcJX0F5DdG+iv9mQHQ/6xv1zaVT9k/iM=,tag:n4+49p49C+14WBqBePyzSQ==,type:str]
sops:
    age:
        - recipient: age1su8ukc9xm5ffg4trtcsmtw08spr2dxwafkf6zn3znpjwnejkn5tq0a93ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZWFnMEtKU0ZZQ3duU3hG
            OGtqRTd2WXh4RlA4eGZRSm1NOHRNTEY2Y21BCm5wcU0reHVNM0dsOEFqSzZLRzBk
            Y0tralBtb1lGTnVSNzNhTUkycWxPODQKLS0tIDBqTDRpdXFNKys0NEtJMFRUT3U0
            VUhaTTkwMVJvMGMybTZDUUhzMlRFY00KDJRn5CsTNQ/u0QIYubSjqm9H5I7DjODI
            WgoSSWStX4XWqkkIh6+mNMhZDdBJZiBcLAFhyUqkO14Q7pxt/m4M2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T20:22:51Z"
    mac: ENC[AES256_GCM,data:g/DraZxa+QAMXoIakuJ3KXAhFIuwWSQEGljAXPs0aCGCQ6J+GlutEhJhminuhDHM5F0L/gGeyrQvje5RgTBpX7eqrVO93/lGr9ytdRojtbS3ZcD0YkZFrJAJgfUruxRWi0HL20HYCtfzozXPWQFQMm2chFp8CU20wNZ3SkVXy3A=,iv:DKfSGZ4o4P5XIl5lhw5mOqtWj1JoRSiVr+TuA9FVas4=,tag:9ZFOk43tOO0BbiiObOaq+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
