#ENC[AES256_GCM,data:lylvBc+LrJQ2gNo8lQ08V8uBX3YBRprDA7KJEc/Q7FLSdRuwtXtULjOAyI7cYJkoEGDo4y9hBz9LJ2OjBtjg8udUDb3XsEVljhDs6Vszl7pPvsIpqeBUf0J/uAwFh5ntQTRdxRzDu6cvFF9vvNxdD9yz/UNQC98cphYVpFmaSDg=,iv:2RDLmsL3scw3hMtjzUCAnhGSvOyV+Bm6RlnEoTkbqL8=,tag:oNH5DdUL5qXFgYix1diLXg==,type:comment]
#ENC[AES256_GCM,data:FPqUJM4bmug7V7U/l1CRYL5iU2ybTfoqk6CDeaN50FnzTzmmM115RUsNjZ24CHFe9J/5/XCiF/Y/iz1olQ7bO5a/3Z5ZvyDgP9vIoX3FOPW4OzShe9YnBsunQOzNcD4pIDZVaMA/ddZatBltmkKe3IW5WCy3q020,iv:mhzSjNwvEw63wSAPLaNmv7jUd0/tQCzeVRjyxUw+JaE=,tag:HW8DxZSt/AxjNyf14od+ZA==,type:comment]
#
#ENC[AES256_GCM,data:PKjCTAUbdYazG5O968WZgi2Zl6dPRBDT7YWslfJb3PDc3nbsIGptYwYljb4B/XyxNLxazvvujALiIo344yoxYbWXsQ==,iv:FJpjgHUTtq4/ehBQuaMwhLyXCvCufMeDuNRGtPIowng=,tag:Pxv5wOSONQ24kFXceOR82A==,type:comment]
#ENC[AES256_GCM,data:LHeDUPe64tmSmH+7hOUv2r0iptVM2kE8ZM9nSPMv2JGlh236v7VEtA==,iv:yM0wc3U8QFxB3GdAd+Yv+roIXgT1e6z4mGESx9vjVeE=,tag:Wt9Z6H2Z2l6xNRd34SQ/dw==,type:comment]
#
#ENC[AES256_GCM,data:wfsFSItv+e4lVZ5FIsZPNRc7X+bv8feZyiDB9q5IR6/ZwVQU8uiW46juRG3knu0xq28Qc910B+BHzG7wsc8EfGBmizFJtIkgQOHfXPNYA6FkKmJGzgfw8jOEWhwE4nRASBLHhSQzvr/L8taaIGcWeJaIPQJL,iv:Cfk+V0FwkeEGYDx9bNB+3c0rPJL04HyIzSEDhj+k4CI=,tag:k853bObHZVOm9M5SN0kBCg==,type:comment]
#ENC[AES256_GCM,data:RkHxT9f1la5KLyg/2ntVC4EiXboH2BRpSMMvGLPXCdWitIDY/aDFV5T9+/SW5BZ2ChRYQs/5F/FeQZLaN71rsg2ml0/vS/dxZjckcTrEesBxaTSjNI0N8Lc/v0BqbFi6h3U+4G9Rbrjo6HcV/Mg3AuEtezb5eb0PGMmI8L6EglRZuhR50f4UfMcs6L2DzgYbPtSwiLk=,iv:MBej/LKol7oxyVfoxRh/yu4IHAi788YqjLgzCkNM7qg=,tag:fsqUPz7f7oSihhUMdITXdQ==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:OPUTYQ==,iv:5Jj+fUjO5gw9AqJJRopT2IHnFf1G9obbtkm9Z0z/sdQ=,tag:J6JKIhHGl+xe9HsBYfPgdw==,type:str]
    dbPassword: ENC[AES256_GCM,data:Hm758GS2VzVM4ESXog==,iv:Sjj9tooZQp7eUj5Jz124wUg17CsXuttlvjmht08tgPY=,tag:svDFg9G1UUlHxcOdhaZJlw==,type:str]
sops:
    age:
        - recipient: age1su8ukc9xm5ffg4trtcsmtw08spr2dxwafkf6zn3znpjwnejkn5tq0a93ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdTRrcVJCZkovSWNDQmNO
            TWx1UWpTY2ZrcnFXbzJqNU1pelAvL2pyWGdvCkdQMzRkQ0JVSDRUbG1jdlZVNVM1
            SFBrY241OElrN0J6WU5LSW5xM2VDM1UKLS0tIG9KVEZWWVRFbmxTNFpyN1VFbTlq
            VVBSRUI2YjN3bnB5ZjJhcUd6YmhKd2MK9dGEKzTQpqCqBhXW43YZHarlThZCMtbU
            q3/6SWDZa4rzeM1dgwfDyXAoZZDu7JyAOkeiivy2fk21KxSd6Kr+HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T06:32:15Z"
    mac: ENC[AES256_GCM,data:GORVqR5W2Y8r0mlbDaSANaehZyRUheg4C1pL20hKLvPdmQEnvOckA0hfi7J53fUAZev9lwR95zdty++MGRUBApfTStUgUBTXIFHFGrzwzNCMyW8OrTw32FWVAkTUNVAHK5e22nXXfBS1tF+6asoKfTNJ2f3h6Z0KKo5dVMmq+/Q=,iv:RLEl0BZGagNiUAfPJLgklMGq4UgiyTAO12clHqhGr9k=,tag:kWNFkqdSMrORzc+IN7VPqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
