#ENC[AES256_GCM,data:rOFvsgmdPjWkTEn+drufMfia2++xgd32VeyP03vhinxylDTjDfC1Yq6/OsA43AOZ6GgcyKOelfxWCVEHiEie77zwknbY/d/YXNbYoHUQuKdmzyyklsDoupVhp5VX+qp6cPnANFxDQvBkjjjOD/atlBQumrw5r1c3Q2RO1Dl2Yq8=,iv:0LGbH8ht0+i2cbk8h8/uTFWcmA0+qkYj7Q2DKPfn8h0=,tag:O5nB/dteHZdWv6pyOkcfHA==,type:comment]
#ENC[AES256_GCM,data:TISSCQ+4R9KyqboPeqORTMElQfbB+sxLSMtQUks/YCFlAlt5uvzLD7vnUZAgxeA+wQCs2aQrRYhRBeFVcBKiG7kDvb6TfPz50wEwACZXQu+rwvsGwdGEXF1JkMkJY2dCzuAtkP4WF1zg81Jmb6NPu+bi/FOZMm9J,iv:gFY0vtfETo3PmhIn19Q9Tf+DHH9hkqMfmNQlxyP9jcM=,tag:WRsONfWgJCfj80NqXDp52A==,type:comment]
#
#ENC[AES256_GCM,data:rHOEOKpmlM0IsbNGz6fXfvam8f5R2L/gGZqRi0AL+MqQTNfm2y9gnFbFNGAKH8VtMfMI+vOqHU9ZAU3N3DjactZ7Pw==,iv:Tc6HGRMKK0s2rYGES4RWH5nVnFDDy06rbKdgxLUA/sw=,tag:fcMsIIdyFq68JhoOOgKe1Q==,type:comment]
#ENC[AES256_GCM,data:GcYnCuDoI6S11mokrcuaBd+Nk6quCOVx+HYOEQt5egrh4vRyN2UIkQ==,iv:7lihAsSHE2Wj+7xrNkB68c8hnbe4VoSY6VamY8WSMps=,tag:/6I1UmjELd+jAzg/vPFkQg==,type:comment]
#
#ENC[AES256_GCM,data:32UUNrNXRepsHAd1+6nFTTV1hz/gIjzyRk/ivDlwpPGRqTErZSLNSOwpdEtaAhCxwO/frHluKq+duQtThgWj7HOb4UBsB8reldJVrOb8C4arEvdcECLwMA+eVMOQCdAF8q1wZDeq5zlTqt5NH4Knay5kjnGr,iv:8Nn5MD5ZNx66tGlvaziStdmPA1MAphikmuyTncunff0=,tag:3ZF2U/sGaPEl4tMl4PG2lQ==,type:comment]
#ENC[AES256_GCM,data:69Q5Nnw5HVFbtXEF0DZNhDLrIzezY9WpidAjMqnCtTWfy1KDjmoZF0ppXYUDx1zWKcMiSQkAlmYjEq0VK161SoGRL3iVROhsq3t5n2QHkyvro6DMta20uaX+lyY7AXNjhF4hWXI0LvsJFsIcMz0cStTlr3zToWT9x6q90YU2H0akpN/h1eNpVaLvOPfkF2HLnN4juyU=,iv:tGSqqAPUX4x39HVasQ5DUR9Y04l5kdMIQkT0Qmm2HsQ=,tag:ciwNkpET/nxB/q2MtO8NjA==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:yCwmGQ==,iv:74du0WuXO1N7Y85P8awBjTWyzs42wNiXMZp02U+vnRE=,tag:6xrgwnVNe+UezWRJ4PpWrg==,type:str]
    dbPassword: ENC[AES256_GCM,data:j+SR808G34QSGtMMkQ==,iv:W+NDE3aCuwXmiM//4KKr26pJYq5Pj/PUvMwMVBZ4N6E=,tag:PmkIhUCPzgd1zhmalrKTQg==,type:str]
sops:
    age:
        - recipient: age12d3npz4tvr9tl8d90dqzaqudqdneegk9gyxv4e8rtleu2g74ld6q3spxdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1LzJjV05vS2hMVndCVnJK
            ZUpoWnlKMWd1ZGhnVmdFNVdYZkZwREYyQkhrCkFBOTQ1SVViZmk0b25kWmNlNjQ0
            Mk53OERReWJTb3JFMFpwS0VLd3ArLzQKLS0tIHVINWdGRnFMYmVzK2krT2QzQ0Z6
            bDhVUUF5WTNSbDRXY3F6MSsvV25XZ1UKCEofKLnSUXIiFq0mhTtw2mtvH8uqGDJo
            UedBecoj/sVxtfaS9HwHtcXQYyxCXb+cowLvVHUqNqW/IEyQsbTEaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T09:42:40Z"
    mac: ENC[AES256_GCM,data:ypvZ2E/1BCMQm8wlMKpcZqiptEnXyLG4eGLqfML8+HuRoHmtYrfsqDRErUzvr2Absn13wtNgme/Jnjg7UevmRcxONDLB4Me+H+iR8b3ggwvnT9SF12Jg0j3KgmKjxZdkHfVTxW3ZMYTqh5j/AF+1y+yHoNziGJF3hHjVJU/Nmj4=,iv:dTTSHtMU/MKKDEsRvgrxsNr5tLpo2hYKseKsM52dQOc=,tag:OwanNpU/OVughctmLUXHwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
